name: Gerar Cobra

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Criar diretório dist
        run: mkdir -p ./dist && chmod -R 777 ./dist/

      - name: Adicionar arquivo config.json
        run: cp ./.github/workflows/config.json ./dist/

      - name: Gerar os arquivos da cobra
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar novos arquivos na branch de saída
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Atualizar animações da cobra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
